import { api } from '@/lib/api';

export interface PropertyAlert {
  _id: string;
  propertyId: string;
  type: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  message: string;
  date: string;
  scheduledFor?: string;
  status: 'pending' | 'seen' | 'completed' | 'dismissed';
  autoGenerated: boolean;
  sourceRef?: {
    model: string;
    id: string;
  };
}

export const alertApi = {
  list: async (propertyId: string): Promise<PropertyAlert[]> => {
    const res = await api.get(`/property/${propertyId}/alerts`);
    return res.data.data?.alerts ?? [];
  },

  autoGenerate: async (propertyId: string): Promise<{ generatedCount: number }> => {
    const res = await api.post(`/property/${propertyId}/alerts/generate`);
    return res.data.data;
  },

  updateStatus: async (alertId: string, status: string): Promise<PropertyAlert> => {
    const res = await api.put(`/property/alert/${alertId}/status`, { status });
    return res.data.data;
  },

  delete: async (alertId: string): Promise<void> => {
    await api.delete(`/property/alert/${alertId}`);
  },
};
