const prisma = require('../../lib/prisma');
const emailManager = require('./providers/email.manager');
const firebaseProvider = require('./providers/firebase.provider');
const { GoogleGenAI } = require('@google/genai');

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || 'dummy-key' });

class NotificationEngine {
  /**
   * Dispatches a notification across multiple channels.
   * Options: { userId, title, message, type, channels: ['in-app', 'email', 'push'], data, useAI }
   */
  async create(options) {
    const { userId, title, message, type = 'system', channels = ['in-app'], data = {}, useAI = false } = options;

    let finalMessage = message;
    let finalTitle = title;

    // AI Generated Notification logic
    if (useAI) {
      try {
        const prompt = `Rewrite the following notification to be professional, urgent, and concise for a financial/real-estate software platform.
        Context: ${type}.
        Title: ${title}
        Message: ${message}
        
        Return ONLY the rewritten message body in plain text.`;
        
        const response = await ai.models.generateContent({
          model: 'gemini-1.5-flash',
          contents: prompt
        });
        
        if (response && response.text) {
          finalMessage = response.text.trim();
          console.log('[NotificationEngine] Message AI enhanced successfully.');
        }
      } catch (err) {
        console.warn('[NotificationEngine] AI rewriting failed, falling back to original message.', err.message);
      }
    }

    console.log(`[NotificationEngine] Dispatching Alert -> ${finalTitle} via [${channels.join(', ')}]`);
    const results = {};

    // 1. In-App Alert
    if (channels.includes('in-app')) {
       try {
         const alert = await prisma.alert.create({
           data: {
             userId,
             title: finalTitle,
             message: finalMessage,
             type: type,
             priority: type === 'urgent' ? 'high' : 'normal',
             autoGenerated: true,
             sourceTable: data.sourceTable || null,
             sourceId: data.sourceId || null
           }
         });
         results.inApp = alert.id;
       } catch (err) {
         console.error('[NotificationEngine] In-app alert failed:', err);
       }
    }

    // Lookup user details if needed for email or push
    let user = null;
    if (channels.includes('email') || channels.includes('push')) {
       try {
         // Note: Assuming pushToken exists on User or similar logic. We fetch email.
         user = await prisma.user.findUnique({ where: { id: userId } });
       } catch (e) {
         console.warn('[NotificationEngine] User lookup failed');
       }
    }

    // 2. Email
    if (channels.includes('email') && user && user.email) {
       try {
         await emailManager.sendEmail({
            to: user.email,
            subject: finalTitle,
            text: finalMessage,
            html: `<div style="font-family:sans-serif;color:#333;"><h2>${finalTitle}</h2><p>Hi ${user.name || 'there'},</p><p>${finalMessage.replace(/\\n/g, '<br/>')}</p><hr/><p><small>Automated by VaultEXP</small></p></div>`
         });
         results.email = true;
       } catch(err) {
         console.error('[NotificationEngine] Email sending failed:', err);
       }
    }

    // 3. Push Notifications
    if (channels.includes('push') && user && user.pushToken) {
       try {
         await firebaseProvider.sendPush(user.pushToken, finalTitle, finalMessage, data);
         results.push = true;
       } catch(err) {
         console.error('[NotificationEngine] Push notification failed:', err);
       }
    }

    return { notified: true, results };
  }
}

module.exports = new NotificationEngine();
